# Generated by Django 5.0.2 on 2024-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garbage", "0004_garbage_cleaned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garbage",
            name="number_of_points",
            field=models.IntegerField(default=10),
        ),
    ]
